//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiDang
    {
        public int MaBD { get; set; }
        public string TenBD { get; set; }
        public Nullable<System.DateTime> ThoiGianDang { get; set; }
        public string NoiDung { get; set; }
    }
}
