//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int MaDH { get; set; }
        public string MaHH { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public int Size { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual HangHoa HangHoa { get; set; }
        public virtual HangHoa HangHoa1 { get; set; }
    }
}
