//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int MaDH { get; set; }
        public System.DateTime NgayDat { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<int> ThanhToan { get; set; }
        public string TinhTrangGiaoHang { get; set; }
        public string HoTenNhan { get; set; }
        public string SoDienThoaiNhan { get; set; }
        public string DiaChiNhan { get; set; }
        public int MaTV { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<decimal> TongTienDonHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
    }
}
