//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHD { get; set; }
        public int MaTV { get; set; }
        public System.DateTime NgayLapHoaDon { get; set; }
        public int MaDH { get; set; }
        public int SoLuong { get; set; }
        public decimal TongTien { get; set; }
    
        public virtual ThanhVien ThanhVien { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
