//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoTroTrucTuyen
    {
        public int MaTN { get; set; }
        public int MaTV { get; set; }
        public string NoiDungTN { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public string MaHH { get; set; }
    
        public virtual ThanhVien ThanhVien { get; set; }
        public virtual HangHoa HangHoa { get; set; }
    }
}
